# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17be37c0c11289594b0f6141f3118fffd030bc5f52bf780d0ff2c22400d0d3c18ee2bbdfedcc5fdb7f430e18a9aa7d5966ce8ba74e2bb065cac0b50db5e86d67

test:
  secret_key_base: 7a4bb1d1f4f4840d1b2d64299281a6ecd9ec9420daa55a0d2ac79ee1f57b888fcfbf22561784800d480c8fdb87cc9e90a5c3531aff8cb0cb47fc3cf38b7719fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
